export const projectList = [
  {
    "id": "proj-001",
    "projectName": "AI-Powered Code Assistant",
    "thumbnail": "https://cdn.dribbble.com/userupload/39530871/file/original-d47808d69f54d5a748176481a14a89a1.jpg?resize=1024x768&vertical=center",
    "description": "A revolutionary tool that helps developers write better code faster using advanced AI models and machine learning techniques.",
    "shortDescription": "Smart AI assistant for better code development",
    "techStack": ["React", "AWS", "Java", "Machine Learning", "Python"],
    "features": ["Real-time code suggestions", "Multi-language support", "Code quality analysis"],
    "challenges": ["Implementing accurate code prediction", "Handling multiple programming languages"],
    "showcaseId": "showcase-001",
    "userId": "user-123",
    "author": {
      "name": "Arjun Kanungo",
      "avatar": "https://github.com/shadcn.png",
      "github": "arjunkanungo"
    },
    "projectLink": "https://ai-code-assistant.demo",
    "githubLink": "https://github.com/arjunkanungo/ai-code-assistant",
    "likes": 156,
    "views": 1205,
    "status": "featured",
    "isProjectOfWeek": true
  },
  {
    "id": "proj-002",
    "projectName": "Virtual Reality Fitness Trainer",
    "thumbnail": "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80",
    "description": "Immersive VR fitness experience with personalized workout routines and real-time form correction.",
    "shortDescription": "VR-based personal training solution",
    "techStack": ["Unity", "C#", "VR SDK", "Machine Learning", "Node.js"],
    "features": ["Motion tracking", "AI form correction", "Custom workout plans"],
    "challenges": ["Motion accuracy", "Real-time feedback implementation"],
    "showcaseId": "showcase-002",
    "userId": "user-124",
    "author": {
      "name": "Sarah Chen",
      "avatar": "https://github.com/sarahchen.png",
      "github": "sarahchen"
    },
    "projectLink": "https://vr-fitness.demo",
    "githubLink": "https://github.com/sarahchen/vr-fitness",
    "likes": 142,
    "views": 890,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-003",
    "projectName": "Sustainable Energy Dashboard",
    "thumbnail": "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80",
    "description": "Real-time monitoring and analytics platform for renewable energy sources with predictive maintenance.",
    "shortDescription": "Smart energy monitoring system",
    "techStack": ["React", "Python", "TensorFlow", "PostgreSQL", "GraphQL"],
    "features": ["Energy analytics", "Predictive maintenance", "Resource optimization"],
    "challenges": ["Data accuracy", "Real-time processing"],
    "showcaseId": "showcase-003",
    "userId": "user-125",
    "author": {
      "name": "Michael Rodriguez",
      "avatar": "https://github.com/mrodriguez.png",
      "github": "mrodriguez"
    },
    "projectLink": "https://energy-dashboard.demo",
    "githubLink": "https://github.com/mrodriguez/energy-dashboard",
    "likes": 198,
    "views": 1500,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-004",
    "projectName": "Blockchain Voting System",
    "thumbnail": "https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80",
    "description": "Secure and transparent voting platform built on blockchain technology with voter verification.",
    "shortDescription": "Decentralized voting solution",
    "techStack": ["Solidity", "Ethereum", "React", "Node.js", "Web3.js"],
    "features": ["Secure voting", "Vote verification", "Real-time results"],
    "challenges": ["Blockchain integration", "Security implementation"],
    "showcaseId": "showcase-004",
    "userId": "user-126",
    "author": {
      "name": "Alex Kumar",
      "avatar": "https://github.com/alexkumar.png",
      "github": "alexkumar"
    },
    "projectLink": "https://blockchain-vote.demo",
    "githubLink": "https://github.com/alexkumar/blockchain-vote",
    "likes": 167,
    "views": 920,
    "status": "featured",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-005",
    "projectName": "AR Interior Designer",
    "thumbnail": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80",
    "description": "Augmented reality app for visualizing furniture and decor in real-time within your space.",
    "shortDescription": "AR-powered interior design tool",
    "techStack": ["Unity", "ARKit", "ARCore", "Swift", "Kotlin"],
    "features": ["Real-time visualization", "Furniture catalog", "Room scanning"],
    "challenges": ["AR accuracy", "3D model optimization"],
    "showcaseId": "showcase-005",
    "userId": "user-127",
    "author": {
      "name": "Emma Wilson",
      "avatar": "https://github.com/emmawilson.png",
      "github": "emmawilson"
    },
    "projectLink": "https://ar-interior.demo",
    "githubLink": "https://github.com/emmawilson/ar-interior",
    "likes": 210,
    "views": 1800,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-006",
    "projectName": "Smart Agriculture System",
    "thumbnail": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80",
    "description": "IoT-based farming solution with automated irrigation and crop health monitoring.",
    "shortDescription": "IoT farming automation platform",
    "techStack": ["Python", "Raspberry Pi", "MongoDB", "React", "IoT Sensors"],
    "features": ["Automated irrigation", "Crop monitoring", "Weather integration"],
    "challenges": ["Sensor reliability", "Power management"],
    "showcaseId": "showcase-006",
    "userId": "user-128",
    "author": {
      "name": "David Park",
      "avatar": "https://github.com/davidpark.png",
      "github": "davidpark"
    },
    "projectLink": "https://smart-agriculture.demo",
    "githubLink": "https://github.com/davidpark/smart-agriculture",
    "likes": 145,
    "views": 980,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-007",
    "projectName": "Neural Music Composer",
    "thumbnail": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?q=80",
    "description": "AI-powered music composition tool that generates original melodies and harmonies.",
    "shortDescription": "AI music generation platform",
    "techStack": ["Python", "TensorFlow", "Web Audio API", "React", "Flask"],
    "features": ["Melody generation", "Style transfer", "MIDI export"],
    "challenges": ["Music theory implementation", "Real-time generation"],
    "showcaseId": "showcase-007",
    "userId": "user-129",
    "author": {
      "name": "Lisa Zhang",
      "avatar": "https://github.com/lisazhang.png",
      "github": "lisazhang"
    },
    "projectLink": "https://neural-music.demo",
    "githubLink": "https://github.com/lisazhang/neural-music",
    "likes": 178,
    "views": 1100,
    "status": "featured",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-008",
    "projectName": "Quantum Algorithm Simulator",
    "thumbnail": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80",
    "description": "Educational platform for simulating and visualizing quantum computing algorithms.",
    "shortDescription": "Quantum computing learning tool",
    "techStack": ["Python", "Qiskit", "React", "D3.js", "TypeScript"],
    "features": ["Algorithm visualization", "Interactive tutorials", "Result analysis"],
    "challenges": ["Quantum concept visualization", "Performance optimization"],
    "showcaseId": "showcase-008",
    "userId": "user-130",
    "author": {
      "name": "James Thompson",
      "avatar": "https://github.com/jthompson.png",
      "github": "jthompson"
    },
    "projectLink": "https://quantum-sim.demo",
    "githubLink": "https://github.com/jthompson/quantum-sim",
    "likes": 134,
    "views": 760,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-009",
    "projectName": "Drone Delivery System",
    "thumbnail": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80",
    "description": "Autonomous drone delivery management system with real-time tracking and route optimization.",
    "shortDescription": "Automated drone delivery platform",
    "techStack": ["Python", "ROS", "React", "MongoDB", "WebSocket"],
    "features": ["Route optimization", "Real-time tracking", "Collision avoidance"],
    "challenges": ["Navigation algorithms", "Safety protocols"],
    "showcaseId": "showcase-009",
    "userId": "user-131",
    "author": {
      "name": "Ryan Martinez",
      "avatar": "https://github.com/ryanmartinez.png",
      "github": "ryanmartinez"
    },
    "projectLink": "https://drone-delivery.demo",
    "githubLink": "https://github.com/ryanmartinez/drone-delivery",
    "likes": 189,
    "views": 1300,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-010",
    "projectName": "Sign Language Translator",
    "thumbnail": "https://images.unsplash.com/photo-1615839170337-6f1c3fb943a0?q=80",
    "description": "Real-time sign language translation using computer vision and machine learning.",
    "shortDescription": "AI-powered sign language tool",
    "techStack": ["Python", "TensorFlow", "OpenCV", "React Native", "Flask"],
    "features": ["Real-time translation", "Multiple language support", "Gesture recognition"],
    "challenges": ["Gesture accuracy", "Real-time processing"],
    "showcaseId": "showcase-010",
    "userId": "user-132",
    "author": {
      "name": "Nina Patel",
      "avatar": "https://github.com/ninapatel.png",
      "github": "ninapatel"
    },
    "projectLink": "https://sign-translator.demo",
    "githubLink": "https://github.com/ninapatel/sign-translator",
    "likes": 225,
    "views": 1900,
    "status": "featured",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-011",
    "projectName": "Cybersecurity Training Platform",
    "thumbnail": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80",
    "description": "Interactive platform for learning cybersecurity through simulated attacks and defense scenarios.",
    "shortDescription": "Hands-on security learning system",
    "techStack": ["Python", "Docker", "React", "Node.js", "MongoDB"],
    "features": ["Attack simulations", "Real-world scenarios", "Progress tracking"],
    "challenges": ["Security implementation", "Scenario design"],
    "showcaseId": "showcase-011",
    "userId": "user-133",
    "author": {
      "name": "Marcus Johnson",
      "avatar": "https://github.com/marcusj.png",
      "github": "marcusj"
    },
    "projectLink": "https://cyber-training.demo",
    "githubLink": "https://github.com/marcusj/cyber-training",
    "likes": 167,
    "views": 1100,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-012",
    "projectName": "3D Protein Visualizer",
    "thumbnail": "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80",
    "description": "Interactive 3D visualization tool for protein structures with analysis capabilities.",
    "shortDescription": "Molecular visualization platform",
    "techStack": ["Three.js", "WebGL", "React", "Python", "Flask"],
    "features": ["3D visualization", "Structure analysis", "Export capabilities"],
    "challenges": ["3D rendering performance", "Data processing"],
    "showcaseId": "showcase-012",
    "userId": "user-134",
    "author": {
      "name": "Sophie Anderson",
      "avatar": "https://github.com/sophiea.png",
      "github": "sophiea"
    },
    "projectLink": "https://protein-viz.demo",
    "githubLink": "https://github.com/sophiea/protein-viz",
    "likes": 145,
    "views": 850,
    "status": "active",
    "isProjectOfWeek": false
  },
  {
    "id": "proj-013",
    "projectName": "Smart City Traffic Management",
    "thumbnail": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80",
    "description": "AI-powered traffic management system for optimizing traffic flow in urban areas.",
    "shortDescription": "Intelligent traffic control system",
    "techStack": ["Python", "TensorFlow", "React", "MongoDB", "IoT"],
    "features": ["Traffic prediction", "Signal optimization", "Incident detection"],
    "challenges": ["Real-time processing", "System integration"],
    "showcaseId": "showcase-013",
    "userId": "user-135",
    "author": {
      "name": "Carlos Rivera",
      "avatar": "https://github.com/carlosr.png",
      "github": "carlosr"
    },
    "projectLink": "https://smart-traffic.demo",
    "githubLink": "https://github.com/carlosr/smart-traffic",
    "likes": 156,
    "views": 920,
    "status": "active",
    "isProjectOfWeek": false
  },
];
